name: Delete Old Version

on:
  push: 
    branches: 
      master
  pull_request:  
    types: 
      closed      

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cleanup
        uses: actions/delete-package-versions@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: 'github-actions-alpha-releases-mubashir'
          package-type: 'npm'
          ignore-versions: '^(?!.*-alpha).*'
          min-versions-to-keep: 0
