name: Cleanup

on: 
  workflow_call:
    inputs:
      min-version-to-keep:
        type: number
        default: 0
#   push:
#   pull_request:
#     types: 
#       closed

# on: workflow_dispatch

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: trst
        run: git branch
        env:
          version: '${{ github.ref_name }}'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cleanup Packages
        uses: actions/delete-package-versions@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: 'github-actions-alpha-releases-mubashir'
          package-type: 'npm'
          ignore-versions: '^(?!.*${{ github.ref_name }}).*'
          min-versions-to-keep: ${{ inputs.min-version-to-keep }}

      # - name: Cleanup Releases
      #   if: ${{ inputs.min-version-to-keep }} == 0
      #   uses: dev-drprasad/delete-older-releases@v0.2.1
      #   with:
      #     keep_latest: 0
      #     delete_tag_pattern: alpha # defaults to ""
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
