name: Cleanup Alpha Versions

# on:
#   workflow_run:
#     workflows: ["Semantic Release"]
#     types:
#       - completed


on:
  push:
    branches:
      - alpha

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Delete Old Alpha Versions
        uses: actions/delete-package-versions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: github-actions-alpha-releases-mubashir
          num-old-versions-to-delete: 1
          package-version-ids: v1.0.1
