name: Commands

on: 
  issue_comment:                                      
      types: 
      - created
  # pull_request: 
  #   types: 
  #     - opened
  #     - reopened
  #     - synchronize
  workflow_dispatch: 
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: echo "Cleaning up all pre-releases" && echo ${{ github.event.comment.body }} && echo ${{ contains(github.event.comment.body, '/cleanup') }}
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - name: Get ref name
        id: ref-name
        run: echo "pr_ref=${{ steps.comment-branch.outputs.head_ref }}" >> "$GITHUB_OUTPUT"
  release:
    if: contains(github.event.comment.body, '/release')
    needs: init
    uses: ./.github/workflows/release.yml
    with:
      COMMENT_REF: ${{ needs.init.outputs.pr_ref }}
  cleanup:
    if: contains(github.event.comment.body, '/cleanup')
    needs: init
    uses: ./.github/workflows/cleanup.yml
  check-cleanup:
    uses: ./.github/workflows/fail.yml
    with:
      is-comment: true
 