name: Pre-release cleanup check

on:
  pull_request: 
      types: 
        - opened
        - reopened
        - synchronize

jobs:
  prerelease-cleanup-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check ref name
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.ref }}
          echo ${{ github.sha }}
      - name: Get tag
        id: get_tag
        uses: oprypin/find-latest-tag@v1
        continue-on-error: true
        with:
          repository: ${{ github.repository }}
          regex: '(.*)${{ github.ref_name }}(.*)'
      - name: Check prerelease cleanup
        if: ${{ steps.get_tag.outputs.tag }}
        run: |
          echo "ERROR: Run full cleanup to merge"
          echo "To run full cleanup, comment /cleanup on your PR"
          exit 1
