name: Cleanup required

on:
  workflow_call:


jobs:
  cleanup-required:
    runs-on: ubuntu-latest
    steps:
        - name: Check prerelease cleanup
          run: |
            echo "ERROR: Run full cleanup to merge"
            echo "To run full cleanup, comment /cleanup on your PR"
            exit 1