name: Cleanup required

on:
  pull_request: 
      types: 
        - opened
        - reopened
        - synchronize

jobs:
  cleanup-required:
    runs-on: ubuntu-latest
    steps:
        - name: Check prerelease cleanup
          run: |
            echo "ERROR: Run full cleanup to merge"
            echo "To run full cleanup, comment /cleanup on your PR"
            exit 1
