name: Final Cleanup

on: 
  issue_comment:                                      
      types: 
      - created
  pull_request: 
    types: 
      - opened
      - reopened
      - synchronize
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: echo "Cleaning up all pre-releases" && echo ${{ github.event.comment.body }} && echo ${{ contains(github.event.comment.body, '/cleanup') }}
      - name: cleanup
        if: contains(github.event.comment.body, '/cleanup')
        uses: ./.github/workflows/cleanup.yml
      - name: cleanup-check
        # if: always()
        uses: ./.github/workflows/fail.yml
        with:
          is-final: true

  # cleanup:
  #   needs: init
  # check-cleanup: