name: Semantic Release

on:
#   workflow_run:
#     workflows: ["Cleanup"]
#     types: [completed]
#   # push:
  #   branches:
  #     - alpha
  #     - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "testing"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
