name: Semantic Release


on: 
  pull_request: 
    types: 
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
  workflow_call:
    inputs:
      COMMENT_REF:
        type: string
    
# on:
#   workflow_run:
#     workflows: [cleanup]
#     types: 
#       - completed
#     branches:
#       - alpha
#       - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          # fetch-depth: 0
          fetch-tags: true

      - name: test
        run: git branch && echo $GITHUB_REF_NAME


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_REF: ${{ steps.comment-branch.outputs.head_ref }}
          GITHUB_REF_NAME: ${{ steps.comment-branch.outputs.head_ref }}
        run: npx semantic-release
  cleanup:
    needs: release
    uses: ./.github/workflows/cleanup.yml
    with:
      min-version-to-keep: 1
