name: Semantic Release


on: 
  # pull_request: 
  #   types: 
  #     - opened
  #     - reopened
  #     - synchronize
  workflow_dispatch:
  workflow_call:
    
# on:
#   workflow_run:
#     workflows: [cleanup]
#     types: 
#       - completed
#     branches:
#       - alpha
#       - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: test
        run: git branch && echo $GITHUB_REF_NAME


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: $GITHUB_REF_NAME
        run: npx semantic-release
  cleanup:
    needs: release
    uses: ./.github/workflows/cleanup.yml
    with:
      min-version-to-keep: 1
